# Generated by Django 4.2 on 2025-03-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lloguer', '0002_reserva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='data',
            new_name='data_inici',
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('data_inici', 'cotxe')},
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_fi',
            field=models.DateField(blank=True, null=True),
        ),
    ]
